export const extensionMap: { [key: string]: string } = {
    "ts": "file_type_typescript.svg",
    "d.ts": "file_type_typescriptdef.svg",
    "js": "file_type_js.svg",
    "mjs": "file_type_js.svg",
    "cjs": "file_type_js.svg",
    "json": "file_type_json.svg",
    "css": "file_type_css.svg",
    "html": "file_type_html.svg",
    "htm": "file_type_html.svg",
    "md": "file_type_markdown.svg",
    "py": "file_type_python.svg",
    "java": "file_type_java.svg",
    "c": "file_type_c.svg",
    "cpp": "file_type_cpp.svg",
    "h": "file_type_cheader.svg",
    "hpp": "file_type_cppheader.svg",
    "go": "file_type_go.svg",
    "rs": "file_type_rust.svg",
    "php": "file_type_php.svg",
    "rb": "file_type_ruby.svg",
    "xml": "file_type_xml.svg",
    "yaml": "file_type_yaml.svg",
    "yml": "file_type_yaml.svg",
    "sql": "file_type_sql.svg",
    "sh": "file_type_shell.svg",
    "bat": "file_type_bat.svg",
    "ps1": "file_type_powershell.svg",
    "dockerfile": "file_type_docker.svg",
    "gitignore": "file_type_git.svg",
    "gitattributes": "file_type_git.svg",
    "editorconfig": "file_type_editorconfig.svg",
    "env": "file_type_dotenv.svg",
    "txt": "file_type_text.svg",
    "log": "file_type_log.svg",
    "svg": "file_type_svg.svg",
    "png": "file_type_image.svg",
    "jpg": "file_type_image.svg",
    "jpeg": "file_type_image.svg",
    "gif": "file_type_image.svg",
    "ico": "file_type_image.svg",
    "zip": "file_type_zip.svg",
    "tar": "file_type_zip.svg",
    "gz": "file_type_zip.svg",
    "7z": "file_type_zip.svg",
    "rar": "file_type_zip.svg",
    "pdf": "file_type_pdf.svg",
    "jsx": "file_type_reactjs.svg",
    "tsx": "file_type_reactts.svg",
    "vue": "file_type_vue.svg",
    "scss": "file_type_scss.svg",
    "less": "file_type_less.svg",
    "ini": "file_type_ini.svg",
    "toml": "file_type_toml.svg",
    "lua": "file_type_lua.svg",
    "pl": "file_type_perl.svg",
    "r": "file_type_r.svg",
    "cs": "file_type_csharp.svg",
    "vb": "file_type_vb.svg",
    "swift": "file_type_swift.svg",
    "kt": "file_type_kotlin.svg",
    "dart": "file_type_dartlang.svg",
    "fs": "file_type_fsharp.svg",
    "fsx": "file_type_fsharp.svg",
    "ex": "file_type_elixir.svg",
    "exs": "file_type_elixir.svg",
    "erl": "file_type_erlang.svg",
    "clj": "file_type_clojure.svg",
    "hs": "file_type_haskell.svg",
    "lhs": "file_type_haskell.svg",
    "scala": "file_type_scala.svg",
    "groovy": "file_type_groovy.svg",
    "gradle": "file_type_gradle.svg",
    "properties": "file_type_java.svg",
    "jsp": "file_type_jsp.svg",
    "asp": "file_type_asp.svg",
    "aspx": "file_type_aspx.svg",
    "cfm": "file_type_cfm.svg",
    "coffee": "file_type_coffeescript.svg",
    "ejs": "file_type_ejs.svg",
    "hbs": "file_type_handlebars.svg",
    "jade": "file_type_pug.svg",
    "pug": "file_type_pug.svg",
    "liquid": "file_type_liquid.svg",
    "twig": "file_type_twig.svg",
    "sass": "file_type_sass.svg",
    "styl": "file_type_stylus.svg",
    "lock": "file_type_lock.svg",
    "tf": "file_type_terraform.svg",
    "tfvars": "file_type_terraform.svg",
    "bicep": "file_type_bicep.svg",
    "azcli": "file_type_azure.svg",
    "cmake": "file_type_cmake.svg",
};

export const filenameMap: { [key: string]: string } = {
    "package.json": "file_type_npm.svg",
    "package-lock.json": "file_type_npm.svg",
    "tsconfig.json": "file_type_tsconfig.svg",
    "jsconfig.json": "file_type_jsconfig.svg",
    "readme.md": "file_type_markdown.svg",
    "license": "file_type_license.svg",
    "license.txt": "file_type_license.svg",
    "license.md": "file_type_license.svg",
    "changelog.md": "file_type_markdown.svg",
    "dockerfile": "file_type_docker.svg",
    "docker-compose.yml": "file_type_docker.svg",
    "docker-compose.yaml": "file_type_docker.svg",
    "jenkinsfile": "file_type_jenkins.svg",
    "angular.json": "file_type_angular.svg",
    "next.config.js": "file_type_next.svg",
    "vercel.json": "file_type_vercel.svg",
    "netlify.toml": "file_type_netlify.svg",
    "vite.config.js": "file_type_vite.svg",
    "vite.config.ts": "file_type_vite.svg",
    "webpack.config.js": "file_type_webpack.svg",
    "rollup.config.js": "file_type_rollup.svg",
    "babel.config.js": "file_type_babel.svg",
    ".babelrc": "file_type_babel.svg",
    ".eslintrc": "file_type_eslint.svg",
    ".eslintrc.js": "file_type_eslint.svg",
    ".eslintrc.json": "file_type_eslint.svg",
    ".prettierrc": "file_type_prettier.svg",
    ".gitignore": "file_type_git.svg",
    ".gitattributes": "file_type_git.svg",
    ".env": "file_type_dotenv.svg",
    "yarn.lock": "file_type_yarn.svg",
    "pnpm-lock.yaml": "file_type_pnpm.svg",
    "bun.lockb": "file_type_bun.svg",
    "cargo.toml": "file_type_cargo.svg",
    "cargo.lock": "file_type_cargo.svg",
    "go.mod": "file_type_go.svg",
    "go.sum": "file_type_go.svg",
    "requirements.txt": "file_type_python.svg",
    "pipfile": "file_type_python.svg",
    "gemfile": "file_type_ruby.svg",
    "composer.json": "file_type_composer.svg",
    "composer.lock": "file_type_composer.svg",
    "mix.exs": "file_type_elixir.svg",
    "maven.xml": "file_type_maven.svg",
    "pom.xml": "file_type_maven.svg",
    "build.gradle": "file_type_gradle.svg",
};

export function getIconForFile(filename: string): string {
    const lowerFilename = filename.toLowerCase();
    
    if (filenameMap[lowerFilename]) {
        return filenameMap[lowerFilename];
    }

    const parts = lowerFilename.split('.');
    if (parts.length > 1) {
        // Check for double extension like .d.ts
        if (parts.length > 2) {
            const doubleExt = parts.slice(-2).join('.');
            if (extensionMap[doubleExt]) {
                return extensionMap[doubleExt];
            }
        }
        
        const ext = parts.pop();
        if (ext && extensionMap[ext]) {
            return extensionMap[ext];
        }
    }

    return "default_file.svg";
}
